version: '3.8'

services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trading_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: