[phases.setup]
# System-level packages needed for compiling Python libraries
aptPkgs = [
    "build-essential",
    "pkg-config",
    "libpq-dev",        # For psycopg2
    "libta-lib0",       # For TA-Lib
    "libta-lib-dev"     # For TA-Lib
]

[start]
# Command to run the application
cmd = "python main.py"