[build]
command = "pip install -r requirements.txt"

[deploy]
startCommand = "python app.py"

[env]
PYTHON_VERSION = "3.11"
WEB_PORT = "8080"
ENABLE_WEB_DASHBOARD = "true"
ENABLE_ADVANCED_TA = "true"
ENABLE_ONCHAIN = "true"
ENABLE_SENTIMENT = "true"
ENABLE_PREDICTION = "true"
ENABLE_RISK_MANAGEMENT = "true"
ENABLE_ARBITRAGE = "true"
ENABLE_MONITOR = "true"
ENABLE_BACKUP = "true"
ENABLE_TRANSFORMERS = "true"
DATABASE_URL = "sqlite:///crypto_bot.db"