[build]
command = "python main.py"

[build.env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"

[deploy]
startCommand = "python main.py"

[env]
COINGECKO_API_KEY = "${COINGECKO_API_KEY}"
COINMARKETCAP_API_KEY = "${COINMARKETCAP_API_KEY}"
CRYPTOCOMPARE_API_KEY = "${CRYPTOCOMPARE_API_KEY}"
CRYPTOPANIC_API_KEY = "${CRYPTOPANIC_API_KEY}"
NEWS_API_KEY = "${NEWS_API_KEY}"
WHALE_ALERT_API_KEY = "${WHALE_ALERT_API_KEY}"
GLASSNODE_API_KEY = "${GLASSNODE_API_KEY}"
ECONOMIC_CALENDAR_API_KEY = "${ECONOMIC_CALENDAR_API_KEY}"
TELEGRAM_BOT_TOKEN = "${TELEGRAM_BOT_TOKEN}"

[[services]]
name = "crypto-bot"